### PR TITLE
Simple Fix for 'Extending sections (macros)' in combination with += and -=.

### PR DESCRIPTION
**Pull request by puittenbroek**
This is related to issue #63, and introduces a simple fix for it, using exisiting code.

### CODE REVIEW

**Comment by simahawk** [comment]
@jimfulton @tseaver any update on this?

**Comment by vangheem** [comment]
We're experiencing this issue as well. Any way we can get this merged and a release? \cc @tseaver @jimfulton

**Comment by tseaver** [comment]
I haven't been making releases for `buildout`:  @jimfulton is the more recent maintainer.

**Comment by reinout** [comment]
I've released 2.5.2 with this fix.

Btw: is https://github.com/buildout/buildout/commit/da72cc876dba007063cf26d4b9c27f395e019ea7 a correct summary of the fix?

**Comment by reinout** [comment]
I haven't really been using this +/- a lot.

Are there other issues that can be closed now? See the four issues labeled plus/minus: https://github.com/buildout/buildout/labels/plus-minus-issues

**Pull request merged**
