### PR TITLE
Trying to fix #283

### LINKED ISSUE #283: TypeError: Option values must be strings with setuptools 19.1
Since todays `19.1` release of `setuptools` buildout fails like this:

```
$ bin/buildout
...
While:
  Installing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/var/lib/jenkins/zope/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/var/lib/jenkins/zope/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 565, in install
    self._compute_part_signatures(install_parts)
  File "/var/lib/jenkins/zope/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 811, in _compute_part_signatures
    options['__buildout_signature__'] = ' '.join(sig)
  File "/var/lib/jenkins/zope/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1370, in __setitem__
    raise TypeError('Option values must be strings', value)
TypeError: ('Option values must be strings', u'zc.recipe.egg-1.3.2-py2.7.egg setuptools-19.1-py2.7.egg zc.buildout-2.5.0-py2.7.egg')
```

Not sure whether this is an issue with `zc.buildout`, `setuptools`, or something else.

### PR DESCRIPTION
**Pull request by reinout**
The problem is also present on travis. So if the pull request works, that is enough of a test for me. Because if it doesn't fix the issue, we cannot run the tests :-)

**Rapid** code review requested as it is an issue that breaks many peoples' automatic tests and many peoples' buildouts because bootstrap doesn't work.

### CODE REVIEW

**Comment by lukasgraf** [comment]
Looks good to me - your latest change fixes the issue for me when testing locally.

Not sure if I'm a fan of encoding the unicode string with the default system encoding though - we know (or assume) it should only ever contain ASCII, why not make this assertion explicit? I don't have any strong feelings about this though.

**Comment by reinout** [comment]
I would have tried to think a bit more about default encodings, normally. But I didn't in this case as I could simply copy some code from `buildout.py` that fixes the same kind of issue. One dealing with directory hashes. If that one doesn't break, this one probably is also OK.

Especially as the problem now is a `u"19.1"` :-)

**Comment by lukasgraf** [comment]
Hmm. From the test failures it looks like setting option values really is just the first place where issues with this surfaced. I'm considering whether this shouldn't be fixed in setuptools instead.

**Comment by lukasgraf** [comment]
@reinout FYI, looks like @jaraco just committed a fix for this in setuptools: https://bitbucket.org/pypa/setuptools/commits/6df29b1f97d0

**Comment by reinout** [comment]
Yes, I saw the fix in setuptools. A fix there sure is better. It is hard to verify if the fix really fixes the issue as I weirdly don't see the issue locally (only in the buildout tests and it is close to impossible to mock/hack the setuptools egg there).

**Comment by lukasgraf** [comment]
I could somewhat verify his fix by downloading the updated `ez_setup.py` and have [`bootstrap.py` pick it up from there](https://github.com/buildout/buildout/blob/master/bootstrap/bootstrap.py#L89) when bootstrapping again. That seemed to work for me (previously failing buildout ran through).

**Comment by reinout** [comment]
See https://travis-ci.org/buildout/buildout/jobs/91337683, it has been fixed by setuptools by adjusting the `ez_setup.py` script.

I'm retracting the pull request as it isn't needed anymore, hurray!

**Pull request closed without merging**
