### PR TITLE
Fixed import of packaging.markers.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
The previous code went wrong depending on which pip/setuptools/wheel version you had.

### CODE REVIEW

**Review by gotcha — APPROVED** [review]
LGTM

**Comment by davisagli** [comment]
@gotcha It should be in the branch protection rules for this repository. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

**Comment by gotcha** [comment]
@davisagli Thanks for the hint. No idea how those rules had been setup.

**Comment by gotcha** [comment]
Will do in asap.

**Comment by dataflake** [comment]
Thanks, I really appreciate it

**Pull request merged**
