### PR TITLE
Nicer version constraint logging + better requirement conflict info logging

### PR DESCRIPTION
**Pull request by reinout**
I've added two basic improvements. The **first one** is small. **Nicer version constraint logging**:

Previously:

    The constraint, 1.6.6, is not consistent with the requirement, 'Django>=1.7'.
    While:
      Updating django.
    Error: Bad constraint 1.6.6 Django>=1.7

Now:

    While:
      Installing django.
    Error: The requirement ('Django>=1.7') is not allowed by your [versions] constraint (1.6.6)

The original message said "bad constraint". No, the constraint is not
necessarily bad. It only conflicts with some other package's requirement.

The new message tells you that "constraint" means "your own [versions]
list".

The **second change** is related. And bigger. **Recording where requirements come from to debug version conflicts**:

Before you'd get a simple output like:

    Installing django.
    While:
      Installing django.
    Error: The requirement ('Django>=1.7') is not allowed by your [versions] constraint (1.6.6)

... which would mean you'd have to grep in all your requirements'
sub-requirements which package actually requires the offending "django>=1.7"

With this change you'll get a much more helpful output right before the error:

    Installing django.
    version and requirements information containing django:
      [versions] constraint on django: 1.6.6
      Base installation request: 'sso', 'djangorecipe'
      Requirement of djangorecipe==1.10: Django
      Requirement of djangorecipe==1.10: zc.recipe.egg
      Requirement of djangorecipe==1.10: zc.buildout
      Requirement of sso: django-nose
      Requirement of sso: django-mama-cas
      Requirement of sso: django-debug-toolbar
      Requirement of sso: django-auth-ldap
      Requirement of sso: Django<1.7,>=1.4.2
      Requirement of lizard-auth-server: django-nose
      Requirement of lizard-auth-server: django-extensions
      Requirement of lizard-auth-server: Django<1.7,>=1.6
      Requirement of django-nose: Django>=1.2
      Requirement of django-nose: nose>=1.2.1
      Requirement of django-mama-cas: requests==1.1.0
      Requirement of django-debug-toolbar: sqlparse
      Requirement of django-debug-toolbar: Django>=1.7
      Requirement of django-auth-ldap: python-ldap>=2.0
      Requirement of django-auth-ldap: django>=1.1
      Requirement of translations: Django>=1.4
      Requirement of django-extensions: six>=1.2
    While:
      Installing django.
    Error: The requirement ('Django>=1.7') is not allowed by your [versions] constraint (1.6.6)

This makes it much easier to spot the cause (in this case
django-debug-toolbar).

There *are* some unrelated packages in here because I'm doing a textual
comparison. The advantage is that it is very robust. And extracting the right
package name from requirements without messing things up is harder to get
right and takes more code.

### CODE REVIEW

**Comment by reinout** [comment]
Fixes #276 and #160 !

**Comment by reinout** [comment]
Hm. Test failures on 3.2 due to setuptools deprecation warnings. I'm dropping 3.2 from travis right away in this pull request (and adding 3.5). I haven't checked if 3.5 is available in the makefile, but I'm going home first :-)

**Comment by reinout** [comment]
Yeah, everything is green again. The 3.5 tests also pass.

**Can someone review the PR?** I'd start by looking at the main description of this PR, that shows exactly what's been changed in the output.

**Comment by gforcada** [comment]
wow, great job, that's indeed much much more nicer

**Comment by mgedmin** [comment]
LGTM (but I'm not familiar with the codebase).

**Comment by reinout** [comment]
Thanks for looking at it.

I've released 2.5.0 :-)

**Comment by reinout** [comment]
And I've done some marketing: http://reinout.vanrees.org/weblog/2015/11/16/buildout-nicer-version-conflicts.html

**Comment by gforcada** [comment]
@reinout thanks! Much much appreciated!

**Comment by gotcha** [comment]
@reinout Yup, really appreciated

**Comment by laulaz** [comment]
@reinout saved me ... again !

**Pull request merged**
