### PR TITLE
Refactor code quality issues

### PR DESCRIPTION
**Pull request by akshgpt7**
## Description

Hi :wave:, I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some [interesting code quality issues](https://deepsource.io/gh/akshgpt7/buildout/) that can improve the general code quality and performance here.
This PR fixes a few of the issues detected.

## Summary of changes
- Refactor complex statement to use `if` expression.
- Fix dangerous default argument.
- Remove unused imports and reimported modules.
- Refactor unnecessary use of list comprehension.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

### CODE REVIEW

**Comment by akshgpt7** [comment]
The CI seems to be failing due to some docker config.
Please let me know if there's something I can do at my end to fix it.

**Comment by gotcha** [comment]
Thanks for working on this.

Could you rebase on master to see if CI would work now ?
Could you add your summary of changes to the commit message ?

**Comment by akshgpt7** [comment]
@gotcha Thanks! They're passing now.

**Comment by akshgpt7** [comment]
@gotcha I'd just like to inform you that the issues fixed here were detected by running [DeepSource](https://deepsource.io) analysis on the repo. If you like, you can activate analysis for your repository to detect such code quality issues/bug risks on the fly for every change made. You can also use the Autofix feature to fix them with one click.

Here's what you can do if you wish to activate DeepSource to continuously analyze your repository:
- [Sign up on DeepSource](https://deepsource.io/signup) and activate analysis for this repository.
- Create `.deepsource.toml` configuration which you can use to configure your analysis settings (this PR already added that, but feel free to edit it anytime).
- Track/Check analysis [here](https://deepsource.io/gh/buildout/buildout).

If you have any doubts or questions, you can check out the [docs](https://deepsource.io/docs), or feel free to reach out :)

**Pull request merged**
