### PR TITLE
fix for win32 '#!"python"' vs '#!python' shebang

### PR DESCRIPTION
**Pull request by agroszer**
fixes the 2 failures at

http://winbot.zope.org/builders/zc_buildout_dev%20py_270_win32%20master/builds/1144/steps/test/logs/stdio

### CODE REVIEW

**Comment by reinout** [comment]
Looks fine. Can you report back whether it worked? Or: when do the winbot tests run? I thought every night or so?

**Comment by agroszer** [comment]
yep nightly

**Comment by agroszer** [comment]
OMG, it's green:

http://winbot.zope.org/builders/zc_buildout_dev%20py_270_win32%20master/builds/1145

**Comment by agroszer** [comment]
I might be tempted to send the failure emails of that builder to a list (distutils?)

**Comment by reinout** [comment]
Well... I've got an alternative to spamming distutils.

It would be valuable if the winbot would test pull requests. Is that handy to arrange?

Note: I don't mind having to log in and press a button or something like that if it is handy, especially for PRs that I expect to be a bit windows-unfriendly.

In exchange for giving me some button I can press (instead of waiting for a nightly build), I don't mind reinout@vanrees.org being put in the "it breaks" email list :-)

**Comment by mgedmin** [comment]
If we used Jenkins, we could have plugins for setting GitHub commit status and also plugins for testing GitHub pull requests.

Unfortunately we use buildbot.

**Comment by agroszer** [comment]
@reinout I added your e-mail addr

**Pull request merged**
