### PR TITLE
Tests on gha

### PR DESCRIPTION
**Pull request by gotcha**
Run tests with Github Actions

### CODE REVIEW

**Comment by gotcha** [comment]
@mauritsvanrees I did setup python cache properly. And stopped to run 3.4, I think supporting 4 major versions is enough.

**Comment by mgedmin** [comment]
Where can one see the test output?  It's not here: https://github.com/buildout/buildout/pull/495/checks

**Comment by gotcha** [comment]
@mgedmin I am new to GHA. I see the same as you when following the link above. Did you check https://github.com/buildout/buildout/actions ?

**Comment by gotcha** [comment]
@gedmin It seems that the actions UI does not allow to point and click to some of the previous runs.

Nevertheless, I found that, via the following URL,

https://github.com/gotcha/buildout/commit/914f8054a5826d2bd0261e0be50ba4535e0863a6/checks

I can access previous runs by specifying both the proper fork and the proper git hash.

**Comment by gotcha** [comment]
Included in #502

**Pull request closed without merging**
