### PR TITLE
Add support for PEP 508 markers in section condition expressions.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
For example: `[versions:python_version <= "3.9"]`. Fixes https://github.com/buildout/buildout/issues/621

I have not added tests yet. Difficult to run them locally: the pure Python that the Makefile tries to create is somehow lacking openssl support on my Mac, though the Makefile tries it. One of the Dockerfiles from gh-actions should help, but I run into network connection errors.

If you want to try it, here is a Buildout config with a conditional section that you can play with:

```
[buildout]
show-picked-versions = true
newest = false
eggs-directory = eggs
download-cache = downloads
parts = test

[test]
recipe = plone.recipe.command
command = echo "normal test"
update-command = ${:command}

[test:python_version < "3.11" or platform_system != "Windows"]
command = echo "difficult condition"

[versions]
plone.recipe.command = 1.1
```

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I have rebased on master and added tests. I can run the tests locally with one of the Docker images now. Ready for review.

**Review by gotcha — APPROVED** [review]
Good idea and thanks for the implementation !

**Comment by gotcha** [comment]
Included in https://pypi.org/project/zc.buildout/3.0.0/

**Comment by mauritsvanrees** [comment]
> Included in https://pypi.org/project/zc.buildout/3.0.0/

Thanks!

Trying it out in [coredev](https://github.com/plone/buildout.coredev/pull/826) now with latest pip, setuptools, wheel. Unfortunately this [fails on Windows](https://github.com/plone/buildout.coredev/actions/runs/3409910424/jobs/5672247013):

```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\zc\buildout\configparser.py", line 194, in parse
    marker = packaging.markers.Marker(expr)
AttributeError: module 'packaging' has no attribute 'markers'
```

I don't know why this would fail on Windows and pass on Linux and Mac.

**Comment by mauritsvanrees** [comment]
I have made a fix (I hope): https://github.com/buildout/buildout/pull/624

**Pull request merged**
