### PR TITLE
Allow to run buildout in FIPS enabled environments

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Review by jamadden — COMMENTED** [review]
Thanks! The actual changes LGTM. Getting CI passing is blocked on #568.

**Comment by frapell** [comment]
@jamadden Is there anything blocking this and #571 to be merged? Also, do you know if there is a schedule on when to expect a released version with these fixes in?

**Comment by jamadden** [comment]
This is blocked on #568, which has test failures on Debian that have to be resolved. I don't know how to do that, so it will take someone that can to look at it. 

I'm not aware of any schedules.

**Comment by gotcha** [comment]
Merged and released in https://pypi.org/project/zc.buildout/3.0.0b4/

**Pull request closed without merging**
