### PR TITLE
Allow to run buildout in FIPS enabled environments

### PR DESCRIPTION
**Pull request by frapell**
In relation to https://github.com/buildout/buildout/issues/570

### CODE REVIEW

**Review by jamadden — APPROVED** [review]
LGTM. 

This same approach was used in https://github.com/zodb/relstorage/pull/481

**Comment by jamadden** [comment]
Can you please prepare a PR against master, which is where development is actually happening, and which has CI?

**Comment by frapell** [comment]
@jamadden Yup, here it is https://github.com/buildout/buildout/pull/572

**Comment by jamadden** [comment]
There's no CI on this branch anymore, so it would be good if at least one other @buildout/developers  could look at it and approve. I don't have any access to make releases to PyPI, so it won't help much even if I merged this on my own.

**Comment by aclark4life** [comment]
@jamadden I'm around if no one else gets to it within 24 hours or so

**Comment by icemac** [comment]
Is this PR ready to be merged and released?

**Comment by frapell** [comment]
FWIW, we are currently using it from the fork, so I guess it would depend if it is an acceptable solution...

**Comment by gotcha** [comment]
Merged and released in https://pypi.org/project/zc.buildout/2.13.6/

**Pull request closed without merging**
