### PR TITLE
Use local ez_setup.py if one exists; add --setuptools-download-base option

### PR DESCRIPTION
**Pull request by lrowe**
For a completely offline install would need to make download_setuptools recognize filesystem paths for download_base.

### CODE REVIEW

**Comment by lrowe** [comment]
The setuptools people ended up implementing a slightly different ``--to-dir`` option. I've updated this to reflect that and fixed the tests to use the bootstrap.py script which is different to buildout bootstrap.

**Comment by WouterVH** [comment]
what's currently blocking this issue?

**Comment by aclark4life** [comment]
Maybe nothing… maybe @jimfulton or @hannosch could review?

**Comment by WouterVH** [comment]
When you don't have access to the public pypi, but only the a local pypi,
you still have to hack this script, to add a download-base, which is usually same as the find-links.

When we want to use a new setuptools-version, (which is very very often these days),
we needed to hacks the ez_setup.py + bootstrap.py to customize the hardcoded urls.

with this patch, we still only need to hack bootstrap.py to specify a download_base.

**Comment by lrowe** [comment]
This PR needs updating to work with the slightly different approach they ended up implementing in ez_setup before it can be merged.

**Comment by lrowe** [comment]
Looks like I just forgot I updated this to reflect the setuptools changes. I think its good to merge.

**Comment by reinout** [comment]
I'll merge it, it looks good.

@lrowe, do you have some info for a quick changelog entry ("setuptools > x.y needed")?

**Comment by lrowe** [comment]
@reinout it requires an ez_setup.py from 14.0 though using installing earlier setuptools versions should work. The changelog from setuptools is:

https://pythonhosted.org/setuptools/history.html#id14
* Bootstrap script now accepts --to-dir to customize save directory or allow for re-use of existing repository of setuptools versions. See Pull Request #112 for background.

Background in setuptools PR: https://bitbucket.org/pypa/setuptools/pull-request/112/allow-ez_setuppy-to-work-offline-by/activity

**Pull request merged**
