### PR TITLE
windows: scripts are implemented with 2 files, avoid burping on that

### LINKED ISSUE #330: on windows metadata_listdir('scripts') returns .exe's too
see:
https://github.com/buildout/buildout/blob/master/src/zc/buildout/easy_install.py#L1106

in turn ```dist.get_metadata('scripts/' + name)``` fails to read that binary .exe

see:
http://winbot.zope.org/builders/ZODB_dev%20py_340_win32/builds/201/steps/buildout/logs/stdio

### PR DESCRIPTION
**Pull request by agroszer**
would fix #330

### CODE REVIEW

**Comment by jimfulton** [comment]
What is the user visible impact of this?

Could you updated CHANGES.rst?

**Comment by agroszer** [comment]
@jimfulton winbot burped on this:

http://winbot.zope.org/builders/ZODB_dev%20py_340_win32/builds/203/steps/buildout/logs/stdio

**Comment by reinout** [comment]
Those two files: they have been generated this way for ages. Do you know what has changed to result in an error now?

**Comment by agroszer** [comment]
@reinout Actually I haven't looked at winbot for a while, it was also down for a while, so no clue since when it was failing. Maybe it's setuptools as it gets upgraded to the latest.

**Pull request merged**
