### PR TITLE
Fix dependencies between zc.buildout and zc.recipe.egg after zc.recipe.egg 2.0.6 release

### PR DESCRIPTION
**Pull request by reinout**

### CODE REVIEW

**Comment by reinout** [comment]
This ought to be a fix for #460

**Comment by reinout** [comment]
... and I also made buildout depend explicitly on 2.0.6+

**Comment by jamadden** [comment]
Thanks for dealing with the bookkeeping on this!

**Comment by reinout** [comment]
So, with zc.recipe.egg 2.0.7 and zc.buildout 2.12.1 it *really* should be fixed :-)

**Pull request merged**
