### PR TITLE
Wheel support also for zc.recipe.egg

### PR DESCRIPTION
**Pull request by reinout**
Plus a small doc update in zc.buildout.

For tidiness' sake I've renamed the .txt files in zc.recipe.egg to .rst, just like in buildout.

(No zc.buildout release is needed, only a zc.recipe.egg one)

### CODE REVIEW

**Comment by reinout** [comment]
See #265, where wheel support was added for zc.buildout.

**Comment by mgedmin** [comment]
Looking at the Travis failures I guess you need to update MANIFEST.in so the renamed \*.rst files will get included in the sdist.

**Comment by reinout** [comment]
@mgedmin: bingo! I didn't immediately spot the problem. I've adjusted the manifest and at least locally the tests run now. I'm waiting for travis to finish processing.

**Comment by reinout** [comment]
Travis runs fine. Does it look OK now?

**Comment by mgedmin** [comment]
I don't see anything wrong at first sight.

**Comment by reinout** [comment]
Ok, zc.recipe.egg (2.0.3) is now also available as a universal wheel.

Maintenance done :-)

**Pull request merged**
