### PR TITLE
Changed os.mkdir to os.makedirs to make it support nested directory creation

### PR DESCRIPTION
**Pull request by guyzmo**
Patch to sort out issue GH-259.

### CODE REVIEW

**Comment by reinout** [comment]
Can you make it complete by adding a quick `CHANGES.rst` entry?

Are you able to get the tests running locally? Two commands ought to set you up:

    make PYTHON_VER=2.7 build
    make PYTHON_VER=2.7 test

I'd look at the 'relative path' section at the end of `downloadcache.txt` as a template for adding a sub-sub-directory. Check the presence with a "ls" as in that example.

(Otherwise just say so and I'll try and add a test).

**Comment by mgedmin** [comment]
Do we not have Travis for this?

Oh.  #206.

**Comment by reinout** [comment]
@mgedmin : #206 is irritating, yes.

The pull request itself runs without test errors, though. I quickly made the same change locally and ran the tests to see if I could find something.

**Comment by guyzmo** [comment]
ok, so I've updated the documentation and wrote a test in `downloadcache.txt` as suggested by @reinout and added an entry in `CHANGES.rst`. 

```
  Ran 346 tests with 0 failures, 0 errors and 0 skipped in 9 minutes 56.038 seconds.
```

**Comment by guyzmo** [comment]
oh! travis is back ;-) 🍻

**Comment by reinout** [comment]
Yes, travis is  back :-) See #206; I fired off an issue to travis based on @mgedmin's detailed information and they fixed our setup within a few hours.

Thanks for the test and the changelog, I'll merge it and do a release.

**Comment by reinout** [comment]
Ouch, I closed it instead of merging it :-)

Anyway, can you check 2.4.3 to see if it works for you as intended?

**Comment by guyzmo** [comment]
it works lovely! thank you 🍺!

**Pull request merged**
