### PR TITLE
Added sorting of working set used by zc.recipe.egg

### LINKED ISSUE #429: Order of paths in scripts (eg. paster) is arbitrary
There seems to be no consistency to the paths generated by zc.recipe.egg between different machines.  

This is not generally a problem, except for /usr/lib/python2.7/dist-packages; when it arbitrarily appears further up in the list, there is a potential for conflicts with system packages being preferred and detected before buildout eggs. 

Manually editing the bin/paster script and moving the system path to the bottom ignores system packages in favor of buildout eggs.

It is confusing, since a buildout that works perfectly on one machine fails on another for no apparent reason.

### PR DESCRIPTION
**Pull request by Cykooz**
It could fix #429 issue.

### CODE REVIEW

**Comment by reinout** [comment]
I've got a corner case. I'm using "syseggrecipe" (https://github.com/nens/syseggrecipe/), which explicitly places certain system packages that you request as a develop egg in the `develop-eggs/` directory. Great way to get hard-to-build packages like numpy and so in your buildout.

In many cases, syseggrecipe needs to use an `*.egg-info` **symlink** instead of an `*.egg-link` **file**:

    GDAL-1.10.1.egg-info -> /usr/lib/python2.7/dist-packages/GDAL-1.10.1.egg-info
    lizard-progress.egg-link
    lxml-3.3.3.egg-info -> /usr/lib/python2.7/dist-packages/lxml-3.3.3.egg-info
    matplotlib-1.3.1.egg-info -> /usr/lib/pymodules/python2.7/matplotlib-1.3.1.egg-info
    psycopg2-2.4.5.egg-info -> /usr/lib/python2.7/dist-packages/psycopg2-2.4.5.egg-info
    uploadserver-site.egg-link

You can probably look at those egg-info files, too?

**Comment by Cykooz** [comment]
@reinout 
> In many cases, syseggrecipe needs to use an *.egg-info symlink instead of an *.egg-link file

In this case *.egg-info symlinks will not be added into the `develop_paths` list. Paths to eggs installed by syseggrecipe will be placed at end of the `sorted_paths` list, like other paths that is not real a develop eggs or located outside of `eggs-directory`. 

I think that this is the correct behavior in this case.

**Comment by reinout** [comment]
@Cykooz, sounds OK.

Can you merge in master? That should help get the tests running again (due to the wheels support problem).

**Comment by Cykooz** [comment]
No, I can't merge in master, because I don't have access to merge.

**Comment by Cykooz** [comment]
Upps... I accidentally merged my old commit into the master branch. Now I will recreate the pull-request.

**Comment by reinout** [comment]
Long live the git user interface :-)
Anyway, if you base off the current master the tests ought to run OK.

**Comment by Cykooz** [comment]
Fixed PR - https://github.com/buildout/buildout/pull/432

**Pull request closed without merging**
