### PR TITLE
Same as #277, but with test and changelog entry

### PR DESCRIPTION
**Pull request by reinout**
This one supersedes #277. The fix is the same, but I added a test and changelog entry.

### CODE REVIEW

**Comment by youngking** [comment]
I should say #195 is the same too, I didn't notice it earlier.

**Comment by reinout** [comment]
@youngking: you're right, that's a similar fix you fond in #195!

**Comment by reinout** [comment]
Anyone: does it look good enough to merge?

**Comment by mgedmin** [comment]
LGTM.

**Comment by reinout** [comment]
@youngking: I just releaser 2.4.6, can you check if that one works for you?

**Comment by youngking** [comment]
It works for me, thanks.

**Pull request merged**
