### PR TITLE
Try to fix CircleCI by installing packaging.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
See failure here:
https://app.circleci.com/pipelines/github/buildout/buildout/329/workflows/8e18b717-6ab0-4097-a42b-6439c4362015/jobs/5433

Do not merge: for testing I have removed all GitHub Actions.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
That helps, for example this [3.8 build](https://app.circleci.com/pipelines/github/buildout/buildout/332/workflows/331b7481-7d5f-4307-921b-7a2ab144f8fb/jobs/5436) passes.

But [2.7 fails](https://app.circleci.com/pipelines/github/buildout/buildout/332/workflows/331b7481-7d5f-4307-921b-7a2ab144f8fb/jobs/5442) with two failures like this:

```
Failure in test /home/circleci/project/doc/topics/optimizing.rst

----------------------------------------------------------------------
File "/home/circleci/project/doc/topics/optimizing.rst", line 35, in optimizing.rst
Failed example:
    eqs([n.split('-', 1)[0]
         for n in ls('home', '.buildout', 'eggs', abieggs)],
        'bobo', 'WebOb', 'six')
Expected nothing
Got:
    (set([]), set(['six']))
```

And the [3.11 job fails](https://app.circleci.com/pipelines/github/buildout/buildout/332/workflows/331b7481-7d5f-4307-921b-7a2ab144f8fb/jobs/5443):

```
Try to upgrade pip

b'Traceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 19, in <module>\n    sys.exit(_main())\n             ^^^^^^^\n  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main\n    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command\n    module = importlib.import_module(module_path)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 940, in exec_module\n  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 24, in <module>\n    from pip._internal.cli.req_command import RequirementCommand\n  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>\n    from pip._internal.index.package_finder import PackageFinder\n  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>\n    from pip._internal.index.collector import parse_links\n  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 12, in <module>\n    from pip._vendor import html5lib, requests\nImportError: cannot import name \'html5lib\' from \'pip._vendor\' (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)\n'
Traceback (most recent call last):
  File "/home/circleci/project/dev.py", line 111, in check_upgrade
    output = subprocess.check_output(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3.11', '-m', 'pip', 'install', '--disable-pip-version-check', '--upgrade', 'pip']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/project/dev.py", line 263, in <module>
    main(parse_args())
  File "/home/circleci/project/dev.py", line 165, in main
    did_upgrade = check_upgrade(package)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/dev.py", line 122, in check_upgrade
    raise RuntimeError("Upgrade of %s failed." % package)
RuntimeError: Upgrade of pip failed.
```

That inner unreadable traceback is this:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)
```

**Comment by mauritsvanrees** [comment]
Here is the [latest CircleCI report](https://app.circleci.com/pipelines/github/buildout/buildout/335/workflows/24778ad4-ce1d-4f22-8e42-0501ec617888).
I have merged the relevant commits into PR #649.
(Plus I disabled CentOS and Debian 3.5/3.6, and had a go at fixing the MacOS runner.)

**Comment by icemac** [comment]
@mauritsvanrees Do you still need the branch?

**Comment by mauritsvanrees** [comment]
No, I have deleted it now.

**Pull request closed without merging**
